### ISSUE TITLE
Appr does not understand chart.yaml apiVersion v2

### ISSUE THREAD

**Issue by flah00** [app-registry/quay-helmv3-plugin#4]
Helm v3 adds optional support for `apiVersion: v2`, which merges `requirements.yaml` into `Chart.yaml`. It seems that the plugin/appr do no support v2. 

I have a chart, which uses v2, I added the `appr` key to the `Chart.yaml` file, but `helm quay` returns an error.

```console
$ helm quay dep up
No requirements.yaml found
```

### Chart.yaml

```yaml
apiVersion: v2
appVersion: 0.8.2
dependencies:
- condition: postgresql.enabled
  name: postgresql
  repository: file://./deps/postgresql
  version: 1.0.1
- alias: anchore-feeds-db
  condition: anchore-feeds-db.enabled,anchoreEnterpriseGlobal.enabled
  name: postgresql
  repository: file://./deps/postgresql
  version: 1.0.1
- alias: anchore-ui-redis
  condition: anchore-ui-redis.enabled,anchoreEnterpriseGlobal.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: "10"
appr:
- condition: postgresql.enabled
  name: quay.io/ORG/postgresql
  repository: appr://
  version: 1.0.1
- alias: anchore-feeds-db
  condition: anchore-feeds-db.enabled,anchoreEnterpriseGlobal.enabled
  name: quay.io/ORG/postgresql
  repository: appr://
  version: 1.0.1
- alias: anchore-ui-redis
  condition: anchore-ui-redis.enabled,anchoreEnterpriseGlobal.enabled
  name: quay.io/ORG/redis
  repository: appr://
  version: "10"

description: Anchore container analysis and policy evaluation engine service
home: https://anchore.com
icon: https://anchore.com/wp-content/uploads/2016/08/anchore.png
keywords:
- analysis
- docker
- anchore
- anchore-engine
- image
- security
- vulnerability
- scanner
maintainers:
- email: zach@anchore.com
  name: zhill
- email: bradyt@anchore.com
  name: btodhunter
name: anchore-engine
sources:
- https://github.com/anchore/anchore-engine
version: 1.10.5
```
